baseURL = 'https://wolganblack.github.io/mi-sitio/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "Conctacto"
    name = "Conctacto"
    title = "Conctacto"
    url = "/Conctacto/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0